version: '2.12'

services:
  db_dev:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: my_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - /c/DockerStorage/MySQLData/:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - dev_networks
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5

  queue_dev:
    image: rabbitmq:3.9.28
    container_name: queue
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq_user"
      RABBITMQ_DEFAULT_PASS: "rabbitmq_passwd"
    ports:
      - "15673:5672"
      - "15672:15672"
    networks:
      - dev_networks
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  dev_networks: